ALTER TABLE public.users 
    ADD COLUMN IF NOT EXISTS role VARCHAR(255) NOT NULL DEFAULT 'user',
    ADD COLUMN IF NOT EXISTS last_ip VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS last_token VARCHAR(32) NOT NULL DEFAULT '';